import { list } from "./list.config";
import { EnableInDev } from "$core/utils/handler";
import { SlashCommandDefition } from "$core/utils/handler/command";
import { SlashCommandBuilder, SlashCommandStringOption, SlashCommandSubcommandBuilder } from "discord.js";

export const enableInDev: EnableInDev = true;

export const slashCommand: SlashCommandDefition = new SlashCommandBuilder()
  .setName(list.name["en-US"])
  .setDescription(list.description["en-US"])
  .setDescriptionLocalizations(list.description)
  .setDMPermission(false)
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.create.name["en-US"])
    .setDescription(list.subcmds.create.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.create.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.create.options.name.name["en-US"])
      .setDescription(list.subcmds.create.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.create.options.name.description)
      .setRequired(true)))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.delete.name["en-US"])
    .setDescription(list.subcmds.delete.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.delete.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.delete.options.name.name["en-US"])
      .setDescription(list.subcmds.delete.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.delete.options.name.description)
      .setRequired(true)))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.add.name["en-US"])
    .setDescription(list.subcmds.add.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.add.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.add.options.name.name["en-US"])
      .setDescription(list.subcmds.add.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.add.options.name.description)
      .setRequired(true))
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.add.options.question.name["en-US"])
      .setDescription(list.subcmds.add.options.question.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.add.options.question.description)
      .setRequired(true)))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.remove.name["en-US"])
    .setDescription(list.subcmds.remove.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.remove.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.remove.options.name.name["en-US"])
      .setDescription(list.subcmds.remove.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.remove.options.name.description)
      .setRequired(true))
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.remove.options.question.name["en-US"])
      .setDescription(list.subcmds.remove.options.question.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.remove.options.question.description)
      .setRequired(true)))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.list.name["en-US"])
    .setDescription(list.subcmds.list.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.list.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.list.options.name.name["en-US"])
      .setDescription(list.subcmds.list.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.list.options.name.description)
      .setRequired(true)))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.lists.name["en-US"])
    .setDescription(list.subcmds.lists.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.lists.description))
  .addSubcommand(new SlashCommandSubcommandBuilder()
    .setName(list.subcmds.rename.name["en-US"])
    .setDescription(list.subcmds.rename.description["en-US"])
    .setDescriptionLocalizations(list.subcmds.rename.description)
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.rename.options.name.name["en-US"])
      .setDescription(list.subcmds.rename.options.name.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.rename.options.name.description)
      .setRequired(true))
    .addStringOption(new SlashCommandStringOption()
      .setName(list.subcmds.rename.options.newname.name["en-US"])
      .setDescription(list.subcmds.rename.options.newname.description["en-US"])
      .setDescriptionLocalizations(list.subcmds.rename.options.newname.description)
      .setRequired(true)));