name: Code check

on:
  push:
    branches: ["main", "env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: "Create .npmrc file from GitHub secrets"
        run: echo "${{ secrets.NPM_RC }}" > .npmrc
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
  typecheck:
    name: TS Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: "Create .npmrc file from GitHub secrets"
        run: echo "${{ secrets.NPM_RC }}" > .npmrc
      - name: Install dependencies
        run: npm install
      - name: Run typecheck
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run typecheck