name: Code check

on:
  push:
    branches: ["env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    permissions:
      contents: read
      packages: read

    name: ESLint
    runs-on: ubuntu-latest

    steps: 
    - name: Setup node and npm
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        registry-url: "https://npm.pkg.github.com"

    - name: Install npm dependencies
      run: "npm install"
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run ESLint
      run: "npm run lint"
      shell: bash