name: Code check

on:
  push:
    branches: ["env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    permissions:
      contents: read
      packages: read

    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      with:
        registry-url: https://npm.pkg.github.com
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}