name: Code check

on:
  push:
    branches: ["env/prod", "env/dev"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    permissions:
      contents: read
      packages: read

    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "18"
          registry-url: https://npm.pkg.github.com
      - name: Install dependencies
        run: npm install